/**
 * cli/costs.js — Token Cost Tracking + Dashboard + Budget Limits
 * Tracks token usage per provider/model and estimates session costs.
 * Supports per-provider cost limits with budget gating.
 *
 * Token Pricing Model:
 * - Prices are in USD per million tokens (input/output separately).
 * - Input tokens: tokens sent to the model (prompt, context, messages).
 * - Output tokens: tokens generated by the model (completion, response).
 * - Cost per call = (input_tokens * input_price + output_tokens * output_price) / 1,000,000
 * - Example: 1000 input + 500 output tokens on gpt-4o-mini (input=$0.15, output=$0.60 per 1M):
 *   Cost = (1000 * 0.15 + 500 * 0.60) / 1,000,000 = $0.00015 + $0.00030 = $0.00045
 */

const fs = require("fs");
const path = require("path");
const { T } = require("./theme");
const { atomicWrite, withFileLockSync } = require("./filelock");

const PRICING = {
  openai: {
    "gpt-4o": { input: 2.5, output: 10.0 },
    "gpt-4o-mini": { input: 0.15, output: 0.6 },
    "gpt-4.1": { input: 2.0, output: 8.0 },
    "gpt-4.1-mini": { input: 0.4, output: 1.6 },
    "gpt-4.1-nano": { input: 0.1, output: 0.4 },
    o1: { input: 15.0, output: 60.0 },
    o3: { input: 10.0, output: 40.0 },
    "o3-mini": { input: 1.1, output: 4.4 },
    "o4-mini": { input: 1.1, output: 4.4 },
  },
  anthropic: {
    "claude-sonnet": { input: 3.0, output: 15.0 },
    "claude-opus": { input: 5.0, output: 25.0 },
    "claude-haiku": { input: 0.8, output: 4.0 },
    "claude-sonnet-4-5": { input: 3.0, output: 15.0 },
    "claude-sonnet-4": { input: 3.0, output: 15.0 },
  },
  gemini: {
    "gemini-2.5-pro": { input: 1.25, output: 10.0 },
    "gemini-2.5-flash": { input: 0.15, output: 0.6 },
    "gemini-2.0-flash": { input: 0.1, output: 0.4 },
    "gemini-2.0-flash-lite": { input: 0.075, output: 0.3 },
  },
  ollama: {
    "qwen3-coder:480b": { input: 0, output: 0 },
    "qwen3-coder-next": { input: 0, output: 0 },
    "devstral-2:123b": { input: 0, output: 0 },
    "devstral-small-2:24b": { input: 0, output: 0 },
    "kimi-k2.5": { input: 0, output: 0 },
    "kimi-k2:1t": { input: 0, output: 0 },
    "deepseek-v3.2": { input: 0, output: 0 },
    "minimax-m2.5": { input: 0, output: 0 },
    "glm-5": { input: 0, output: 0 },
    "glm-4.7": { input: 0, output: 0 },
    "gpt-oss:120b": { input: 0, output: 0 },
  },
  local: {},
};

const AFFORDABLE_PROVIDERS = new Set(["ollama", "local"]);
const PREMIUM_PROVIDERS = new Set(["openai", "anthropic", "gemini"]);

// Session usage accumulator
let usageLog = [];

// Per-provider cost limits (e.g. { anthropic: 5.00, openai: 10.00 })
let costLimits = {};

// Avoid printing the same soft warning on every call once a provider crosses 80%.
let budgetWarningState = new Set();

function getProviderCostMode(provider) {
  const name = String(provider || "").toLowerCase();
  if (AFFORDABLE_PROVIDERS.has(name)) {
    return {
      provider: name,
      tier: "affordable",
      paid: false,
      label: name === "local" ? "local open model" : "open-model path",
      detail:
        name === "local"
          ? "runs through a local Ollama server with no per-token API charge"
          : "recommended affordable path for open coding models",
    };
  }
  if (PREMIUM_PROVIDERS.has(name)) {
    return {
      provider: name,
      tier: "premium",
      paid: true,
      label: "premium paid provider",
      detail: "may incur per-token API charges; use /budget to cap spend",
    };
  }
  return {
    provider: name,
    tier: "unknown",
    paid: null,
    label: "cost unknown",
    detail: "pricing is not known to nex-code",
  };
}

function isAffordableProvider(provider) {
  return getProviderCostMode(provider).tier === "affordable";
}

function isPremiumProvider(provider) {
  return getProviderCostMode(provider).tier === "premium";
}

function formatProviderCostMode(provider) {
  const mode = getProviderCostMode(provider);
  return `${mode.label} — ${mode.detail}`;
}

/**
 * Track token usage for a single API call.
 * @param {string} provider
 * @param {string} model
 * @param {number} inputTokens
 * @param {number} outputTokens
 */
function trackUsage(
  provider,
  model,
  inputTokens,
  outputTokens,
  cacheReadTokens = 0,
) {
  usageLog.push({
    provider,
    model,
    input: inputTokens,
    output: outputTokens,
    cacheRead: cacheReadTokens,
  });

  // Check budget after tracking
  if (costLimits[provider] !== undefined) {
    const budget = checkBudget(provider);
    if (!budget.allowed) {
      process.stderr.write(
        `${T.yellow}\u26a0 Budget limit reached for ${provider}: $${budget.spent.toFixed(2)} / $${budget.limit.toFixed(2)}${T.reset}\n`,
      );
    } else if (budget.limit > 0 && budget.spent >= budget.limit * 0.8) {
      const warningKey = `${provider}:${budget.limit}:80`;
      if (!budgetWarningState.has(warningKey)) {
        budgetWarningState.add(warningKey);
        process.stderr.write(
          `${T.yellow}Budget warning for ${provider}: $${budget.spent.toFixed(2)} / $${budget.limit.toFixed(2)} used. Use /budget ${provider} <amount> to raise the cap or /model ollama:<model> for the affordable path.${T.reset}\n`,
        );
      }
    }
  }
}

/**
 * Get pricing for a provider/model pair.
 * Returns { input: 0, output: 0 } for unknown models.
 */
function getPricing(provider, model) {
  const providerPricing = PRICING[provider];
  if (!providerPricing) return { input: 0, output: 0 };
  return providerPricing[model] || { input: 0, output: 0 };
}

/**
 * Calculate cost for a single usage entry.
 */
function calcCost(entry) {
  const pricing = getPricing(entry.provider, entry.model);
  return (
    (entry.input * pricing.input + entry.output * pricing.output) / 1_000_000
  );
}

/**
 * Get aggregated session costs.
 * @returns {{ totalCost: number, totalInput: number, totalOutput: number, breakdown: Array }}
 */
function getSessionCosts() {
  const byKey = {};

  for (const entry of usageLog) {
    const key = `${entry.provider}:${entry.model}`;
    if (!byKey[key]) {
      byKey[key] = {
        provider: entry.provider,
        model: entry.model,
        requests: 0,
        input: 0,
        output: 0,
        cacheRead: 0,
      };
    }
    byKey[key].requests++;
    byKey[key].input += entry.input;
    byKey[key].output += entry.output;
    byKey[key].cacheRead += entry.cacheRead || 0;
  }

  const breakdown = Object.values(byKey).map((b) => ({
    ...b,
    cost: calcCost(b),
  }));

  const totalCost = breakdown.reduce((sum, b) => sum + b.cost, 0);
  const totalInput = breakdown.reduce((sum, b) => sum + b.input, 0);
  const totalOutput = breakdown.reduce((sum, b) => sum + b.output, 0);
  const totalCacheRead = breakdown.reduce(
    (sum, b) => sum + (b.cacheRead || 0),
    0,
  );

  return { totalCost, totalInput, totalOutput, totalCacheRead, breakdown };
}

/**
 * Format costs for display (/costs command).
 * @returns {string}
 */
function formatCosts() {
  const { totalCost, totalInput, totalOutput, breakdown } = getSessionCosts();

  if (breakdown.length === 0) {
    return "No token usage recorded this session.";
  }

  const lines = [];
  lines.push("Session Token Usage:");
  lines.push("");

  for (const b of breakdown) {
    const costStr = b.cost > 0 ? `$${b.cost.toFixed(4)}` : "free";
    const mode = getProviderCostMode(b.provider);
    lines.push(`  ${b.provider}:${b.model}`);
    lines.push(`    Path:   ${mode.label}`);
    lines.push(`    Input:  ${b.input.toLocaleString()} tokens`);
    lines.push(`    Output: ${b.output.toLocaleString()} tokens`);
    lines.push(`    Cost:   ${costStr}`);
  }

  lines.push("");
  lines.push(
    `  Total: ${totalInput.toLocaleString()} in + ${totalOutput.toLocaleString()} out = $${totalCost.toFixed(4)}`,
  );

  return lines.join("\n");
}

/**
 * Rough character-based token estimation (~4 chars per token, GPT-style average).
 * Used as fallback when the API does not return token counts.
 * @param {string} text
 * @returns {number}
 */
function estimateTokens(text) {
  if (!text || typeof text !== "string") return 0;
  return Math.ceil(text.length / 4);
}

/**
 * Format a short cost hint for inline display after responses.
 * @returns {string} e.g. "[~$0.003]" or "" if free
 */
function formatCostHint(provider, model, inputTokens, outputTokens) {
  const pricing = getPricing(provider, model);
  const cost =
    (inputTokens * pricing.input + outputTokens * pricing.output) / 1_000_000;
  if (cost <= 0) return "";
  return `[~$${cost.toFixed(4)}]`;
}

/**
 * Reset all tracked usage (for testing or new sessions).
 */
function resetCosts() {
  usageLog = [];
  budgetWarningState = new Set();
}

// ─── Cost Limits ───────────────────────────────────────────────

/**
 * Set a cost limit for a provider (in dollars).
 */
function setCostLimit(provider, maxDollars) {
  costLimits[provider] = maxDollars;
}

/**
 * Remove a cost limit for a provider.
 */
function removeCostLimit(provider) {
  delete costLimits[provider];
}

/**
 * Get all cost limits.
 * @returns {object}
 */
function getCostLimits() {
  return { ...costLimits };
}

/**
 * Get total spend for a specific provider in this session.
 */
function getProviderSpend(provider) {
  let total = 0;
  for (const entry of usageLog) {
    if (entry.provider === provider) {
      total += calcCost(entry);
    }
  }
  return total;
}

/**
 * Check if a provider is within budget.
 * @returns {{ allowed: boolean, spent: number, limit: number|null, remaining: number|null }}
 */
function checkBudget(provider) {
  const spent = getProviderSpend(provider);
  const limit = costLimits[provider];

  if (limit === undefined) {
    return { allowed: true, spent, limit: null, remaining: null };
  }

  const remaining = Math.max(0, limit - spent);
  return {
    allowed: spent < limit,
    spent,
    limit,
    remaining,
  };
}

/**
 * Load cost limits from .nex/config.json
 */
function loadCostLimits() {
  const configPath = path.join(process.cwd(), ".nex", "config.json");
  if (!fs.existsSync(configPath)) return;
  try {
    const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
    if (config.costLimits && typeof config.costLimits === "object") {
      costLimits = { ...config.costLimits };
    }
  } catch {
    // ignore corrupt config
  }
}

/**
 * Save cost limits to .nex/config.json
 */
function saveCostLimits() {
  const configDir = path.join(process.cwd(), ".nex");
  const configPath = path.join(configDir, "config.json");
  if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });

  withFileLockSync(configPath, () => {
    let config = {};
    if (fs.existsSync(configPath)) {
      try {
        config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      } catch {
        config = {};
      }
    }
    config.costLimits = costLimits;
    atomicWrite(configPath, JSON.stringify(config, null, 2));
  });
}

/**
 * Reset cost limits (for testing).
 */
function resetCostLimits() {
  costLimits = {};
  budgetWarningState = new Set();
}

// Load cost limits on init
loadCostLimits();

module.exports = {
  PRICING,
  trackUsage,
  getSessionCosts,
  formatCosts,
  formatCostHint,
  resetCosts,
  getPricing,
  setCostLimit,
  removeCostLimit,
  getCostLimits,
  getProviderSpend,
  checkBudget,
  getProviderCostMode,
  formatProviderCostMode,
  isAffordableProvider,
  isPremiumProvider,
  loadCostLimits,
  saveCostLimits,
  resetCostLimits,
  estimateTokens,
};
